# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 16 Dec 2011 01:57:56 +0000
*               @ALL          1
*               @user         8
