<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: litao
 * Date: Thu, 22 Dec 2011 16:58:21 +0800
 */

$conf['title'] = 'Peach\'s Doku';
$conf['start'] = 'Start-here';
$conf['template'] = 'arctic-mbo';
$conf['license'] = 'cc-by-sa';
$conf['maxtoclevel'] = '5';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['htmlok'] = 1;
$conf['tpl']['arctic-mbo']['left_sidebar_content'] = 'main,user,group,namespace,index';

// end auto-generated content
